# Created by trellis-cli v1.7.0
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  pros90amapa.org.br:
    site_hosts:
    - canonical: pros90amapa.org.br
      redirects:
      - www.pros90amapa.org.br
    local_path: ../site
    branch: master
    repo: git@github.com:dsemblano/pros90amapa.org.br.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
